# man en 51
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --language_id "0" --speaker_id "0051_preprocessed_data_libri_spkr" --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/51/121055/51_121055_000014_000000.wav" --text "$(cat inference1.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /workspace/nartts/AdaSpeech/BigVGAN/g_05000000_large.zip --vocoder_config /workspace/nartts/AdaSpeech/BigVGAN/config_large.json --restore_step 162000
# man en 58
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --language_id "0" --speaker_id "0058_preprocessed_data_libri_spkr" --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/58/121075/58_121075_000004_000000.wav" --text "$(cat inference1.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /workspace/nartts/AdaSpeech/BigVGAN/g_05000000_large.zip --vocoder_config /workspace/nartts/AdaSpeech/BigVGAN/config_large.json --restore_step 162000
# man en 85
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --language_id "0" --speaker_id "0085_preprocessed_data_libri_spkr" --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/85/121551/85_121551_000006_000000.wav" --text "$(cat inference1.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /workspace/nartts/AdaSpeech/BigVGAN/g_05000000_large.zip --vocoder_config /workspace/nartts/AdaSpeech/BigVGAN/config_large.json --restore_step 162000
# man en 1844
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --language_id "0" --speaker_id "1844_preprocessed_data_libri_spkr" --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/1844/145713/1844_145713_000002_000000.wav" --text "$(cat inference1.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /workspace/nartts/AdaSpeech/BigVGAN/g_05000000_large.zip --vocoder_config /workspace/nartts/AdaSpeech/BigVGAN/config_large.json --restore_step 162000

# man en 1868
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --language_id "0" --speaker_id "1868_preprocessed_data_libri_spkr" --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/1868/145473/1868_145473_000008_000001.wav" --text "$(cat inference1.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /workspace/nartts/AdaSpeech/BigVGAN/g_05000000_large.zip --vocoder_config /workspace/nartts/AdaSpeech/BigVGAN/config_large.json --restore_step 162000


# woman en 0052  perfect 
# --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/52/121057/52_121057_000036_000004.wav" 

# woman perfect 0366
# --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/366/127793/366_127793_000002_000002.wav"

# man en 1868 原神 hifigan finetune
# --reference_embedding "/workspace/nartts/AdaSpeech/preprocessed_data/trump/speaker_embed/trump-spk-3.npy"
# --reference_audio "/data/speech_data/Yuanshen/wav/VO_COOP/VO_gorou/vo_LYYCOP001_1905509_gorou_03b.wav"
# --reference_embedding "/workspace/nartts/AdaSpeech/preprocessed_data/preprocessed_data_libri_spkr/speaker_embed/00vo-spk-LYYCOP001_1905509_gorou_03b.npy"

# women气泡音老太太 --speaker_id "0077" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/77/121518/77_121518_000012_000002.wav

# women0 --speaker_id "0052" --language_id 0 --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/52/121057/52_121057_000036_000004.wav"
# women1 --speaker_id "0366" --language_id 0 --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/366/127793/366_127793_000002_000002.wav"
# women2 --speaker_id "0057" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/57/121074/57_121074_000001_000002.wav
# women3 --speaker_id "0065" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/65/121089/65_121089_000024_000006.wav
# women4 --speaker_id "0082" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/82/122859/82_122859_000010_000002.wav
# women5 --speaker_id "0092" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/92/6488/92_6488_000000_000000.wav
# men0 --speaker_id "1868" --language_id 0 --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/1868/145473/1868_145473_000008_000001.wav"
# men1 --speaker_id "0051" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/51/121055/51_121055_000092_000000.wav
# men2 --speaker_id "0062" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/62/121084/62_121084_000015_000003.wav
# men3 --speaker_id "0066" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/66/355/66_355_000007_000004.wav
# men4 --speaker_id "0085" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/85/121551/85_121551_000015_000000.wav
# men5 --speaker_id "0091" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/91/123498/91_123498_000009_000001.wav

# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py\
#  --speaker_id "0091" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/91/123498/91_123498_000009_000001.wav\
#   --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000

# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0065" --language_id 0 /data/speech_data/LibriTTS_R/train-other-500/65/121089/65_121089_000024_000001.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/libri_cctv_aishell/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/libri_cctv_aishell/model.yaml -t /workspace/nartts/AdaSpeech/config/libri_cctv_aishell/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000



# 58男声 气泡音 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/58/121075/58_121075_000004_000002.wav
# 中文男声 --reference_embedding /workspace/nartts/AdaSpeech/preprocessed_data/aishell3/spk_emb/SSB1935-spk-SSB19350418.npy



# #  generate 12 npy
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py -speaker_id "0052" --language_id 0 --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/52/121057/52_121057_000036_000004.wav" --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0366" --language_id 0 --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/366/127793/366_127793_000002_000002.wav" --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0057" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/57/121074/57_121074_000001_000002.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0065" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/65/121089/65_121089_000024_000006.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0082" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/82/122859/82_122859_000010_000002.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0092" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/92/6488/92_6488_000000_000000.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "1868" --language_id 0 --reference_audio "/data/speech_data/LibriTTS_R/train-other-500/1868/145473/1868_145473_000008_000001.wav" --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0051" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/51/121055/51_121055_000092_000000.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0062" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/62/121084/62_121084_000015_000003.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0066" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/66/355/66_355_000007_000004.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0085" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/85/121551/85_121551_000015_000000.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=0 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0091" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/91/123498/91_123498_000009_000001.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
  

# all audio pieces
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "0483" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/0483_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "1665" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/1665_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "2208" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/2208_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "3433" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/3433_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "5181" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/5181_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "5733" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/5733_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "7649" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/7649_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "7839" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/7839_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "8033" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/8033_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "8346" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/8346_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "8430" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/8430_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
# CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "8799" --language_id 0 --reference_audio /data/speech_data/cuijiayan/ref_audios/8799_all.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000


CUDA_VISIBLE_DEVICES=1 python /workspace/nartts/AdaSpeech/inference.py --speaker_id "pandaSound" --language_id 0 --reference_audio /data/speech_data/LibriTTS_R/train-other-500/8799/270794/8799_270794_000008_000005.wav --text "$(cat /workspace/nartts/AdaSpeech/test.txt)" -p /workspace/nartts/AdaSpeech/config/en_cn_spkr/preprocess.yaml -m /workspace/nartts/AdaSpeech/config/en_cn_spkr/model.yaml -t /workspace/nartts/AdaSpeech/config/en_cn_spkr/train.yaml --vocoder_checkpoint /data/speech_data/cuijiayan/checkpoint/hifigan/g_finetune_02695000.pth.tar --vocoder_config /workspace/nartts/AdaSpeech/hifigan/config.json --restore_step 124000
 