path:
  ckpt_path: "/workspace/nartts/AdaSpeech/output/output_testing_spk_3/ckpt/testing_spk_3/"
  log_path: "/workspace/nartts/AdaSpeech/output/output_testing_spk_3/log/testing_spk_3/"
  result_path: "/workspace/nartts/AdaSpeech/output/output_testing_spk_3/result/testing_spk_3/"
  combination_path: "/workspace/nartts/AdaSpeech/preprocessed_data/cmb_cctv_libri/"
optimizer:
  batch_size: 8
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 1
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 5000
  log_step: 20
  synth_step: 200
  val_step: 200
  save_step: 200
  phoneme_level_encoder_step: 60000
ignore_layer:
  #layers: ["encoder.src_word_emb.weight", "speaker_emb.weight"]
  layers: []
