path:
  ckpt_path: "./output/output_en_cn/ckpt/adaspeech_en_cn"
  log_path: "./output/output_en_cn/log/adaspeech_en_cn"
  result_path: "./output/output_en_cn/result/adaspeech_en_cn"
optimizer:
  batch_size: 56
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 50000]
  anneal_rate: 0.3
step:
  total_step: 600000
  log_step: 2000
  synth_step: 2000
  val_step: 2000
  save_step: 2000
  phoneme_level_encoder_step: 30000
ignore_layer:
  #layers: ["encoder.src_word_emb.weight", "speaker_emb.weight"]
  layers: []
