path:
  ckpt_path: "/workspace/nartts/AdaSpeech/output/output_libri_spkr/ckpt/adaspeech_libri_spkr"
  log_path: "/workspace/nartts/AdaSpeech/output/output_libri_spkr/log/adaspeech_libri_spkr"
  result_path: "/workspace/nartts/AdaSpeech/output/output_libri_spkr/result/adaspeech_libri_spkr"
optimizer:
  batch_size: 56
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 600000
  log_step: 2000
  synth_step: 2000
  val_step: 2000
  save_step: 20000
  phoneme_level_encoder_step: 30000
ignore_layer:
  #layers: ["encoder.src_word_emb.weight", "speaker_emb.weight"]
  layers: []
